# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.78.0"

before_all do
  ensure_git_status_clean
  git_pull
end

default_platform(:android)

platform :android do
  app_build_gradle = File.expand_path("../app/build.gradle")
  private_lane :increment_version_code do
    # Lanes run with a different current directory than actions.
    # See https://docs.fastlane.tools/advanced/#directory-behavior
    regex = /(versionCode\s+)(\d+)/

    source = File.read(app_build_gradle)
    match = source.match(regex)
    raise "Missing versionCode in gradle file at #{path}" if match.nil?

    label = match[1]
    version_code = match[2].to_i
    UI.message("Current version code is: #{version_code}")
    next_version_code = version_code + 1

    File.open(app_build_gradle, "w") do |f|
      f.write source.gsub(regex, "#{label}#{next_version_code}")
    end

    UI.success("Updated version code to: #{next_version_code}")
  end

  private_lane :build do
    increment_version_code
    gradle(task: "clean")
    gradle(task: "assemble", build_type: "Release")
  end

  desc "Ship to PlayStore Beta"
  lane :beta do
    ensure_git_branch(branch: "develop")
    build
    upload_to_play_store(track: "beta")
    git_commit(path: [app_build_gradle], message: 'Bump android version code')
    push_to_git_remote
  end
end
